In [600]:
import numpy as np 
import pandas as pd , re, unidecode

In [601]:
product = pd.read_csv("ProductsData.csv", encoding="ISO-8859-1")

In [602]:
product.head()

,product_name,product_id,product_category,price,professional_publication,region_address,local_address,qty
0,"""chambre a coucher ""","""40008817""","""Meubles et dÃ©coration """,1 800,"""private""","""Grand Casablanca""","""Casablanca""",25
1,"""Comte free fire""","""40008816""","""Jeux vidÃ©o et consoles """,Â,"""private""","""Grand Casablanca""","""Casablanca""",110
2,"""Iphone 6 plus""","""40008815""","""TÃ©lÃ©phones """,Â,"""private""","""Grand Casablanca""","""Casablanca""",21
3,"""Renault ""","""40008814""","""Voitures """,Â,"""private""","""Chaouia-Ouardigha""","""Settat""",128
4,"""PS3 SLIM 360 GB ""","""40008812""","""Jeux vidÃ©o et consoles """,1 400,"""private""","""Rabat-SalÃ©-Zemmour-ZaÃ«r""","""Sala Al-Jadida""",96

In [603]:
product.drop(['product_category', 'professional_publication' , 'region_address' , 'local_address'] , axis=1 , inplace=True)

product.head(10)

                          product_name  product_id   price  qty
0                 "chambre a coucher "  "40008817"   1 800   25
1                    "Comte free fire"  "40008816"      Â   110
2                      "Iphone 6 plus"  "40008815"      Â    21
3                           "Renault "  "40008814"      Â   128
4                   "PS3 SLIM 360 GB "  "40008812"   1 400   96
5  "Need For Speed Heat Xbox One Neuf"  "39955729"     549   87
6                             "becane"  "40008811"      Â    22
7                              "Nikel"  "40008809"  75 000  109
8                   "compte free fire"  "40008808"     170  139
9                        "Appartement"  "40008807"     NaN   81

In [604]:
product.loc[:,'price'].isna().sum()

np.int64(770)

In [605]:
product['price'] = (
    product['price']
    .astype(str)
    .str.replace('[^0-9.]', '', regex=True)  
    .str.strip()
)


product['price'] = pd.to_numeric(product['price'], errors='coerce')

In [606]:
product['price'] =( 

pd.to_numeric(product['price'], errors='coerce')
.dropna()
)

In [607]:
product = product[~product['product_name'].str.contains(r'[\?\؟]', regex=True, na=False)]

In [608]:
product['product_name']=product['product_name'].astype(str).str.strip()

In [609]:
product.drop_duplicates(inplace=True)

In [610]:
product.sample(5)

                  product_name  product_id     price  qty
125              "MUSCULATION"  "40008711"     700.0  119
2356      "CitroÃ«n berlingo "  "39241981"  135000.0   24
206          "Lenovo Yoga 370"  "40008648"    5000.0  118
230   "Motorola G5s plus 32go"  "40008622"    1250.0   69
1306       "free fire compte "  "40007616"       NaN   58

In [611]:
#لقيت مشكله بالبيانات بعضهم مخزنين ك اوبجكت ف المكتبه ماقدرت تتعامل معهم لي ساعتين ادور المشكله هههه

product.dtypes

product_name     object
product_id       object
price           float64
qty               int64
dtype: object

In [612]:
product['product_name']=product['product_name'].astype('string')

In [613]:
product['product_id']=product['product_id'].astype('string').str.replace('"','').astype('int64')

In [614]:
product.dropna(inplace=True)

In [615]:
product.fillna(0 , inplace=True)

In [616]:
product.count()

product_name    3104
product_id      3104
price           3104
qty             3104
dtype: int64

In [617]:
product.dtypes

product_name    string[python]
product_id               int64
price                  float64
qty                      int64
dtype: object

In [618]:
product.reset_index(inplace=True)

In [619]:
product.drop('index' , axis=1, inplace=True)

In [620]:
product['product_name']=product['product_name'].str.strip('"')

In [621]:
product = product[product["product_name"].str.fullmatch(r"[A-Za-z0-9\s\-]+")]

In [622]:
product.head()

                        product_name  product_id    price  qty
0                 chambre a coucher     40008817   1800.0   25
1                   PS3 SLIM 360 GB     40008812   1400.0   96
2  Need For Speed Heat Xbox One Neuf    39955729    549.0   87
3                              Nikel    40008809  75000.0  109
4                   compte free fire    40008808    170.0  139

In [623]:
# الداتا تقريبا به 4000 منتج
# غير عدد السامبل على كيفك
# ترا البيانات ماهي نظيفة 100%ء
# عشان السامبل مايتغير بكل رن حط راندوم ستيت معين
# جرب أكثر من رقم لين تطلع لك بيانات مرتبه
# وسو run all لا خلصت

product = product.sample(250, random_state=1425)

In [624]:
product.to_csv('ProductsData_clean.csv',index=False)